Repository WildCodeSchool-2024-02/js-toulouse-p2-moovies_lib, pull requests merged in 2024-04, with the labels that each got.

#1 feat: first commit
  client/src/App.jsx
Labels: CORRECTIONS DONE, REVIEWED

#2 feat: point d exclamation imperatif git add .!
  client/src/App.jsx
Labels: REVIEWED

#3 S2 us0/first pr mansour
  client/src/App.jsx
Labels: CORRECTIONS DONE, REVIEWED

#4 S2 us0/first pr romain
  client/src/App.jsx
  package-lock.json
  package.json
Labels: CORRECTIONS DONE, REVIEWED

#5 S2 us0/first pr bob
  client/src/App.jsx
  package-lock.json
  package.json
Labels: REVIEWED

#6 feat: architecture
  client/.env.sample
  client/.gitignore
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/logo.jpg
  client/src/components/Card.jsx
  client/src/components/Card.scss
  client/src/components/PersonCard.jsx
  client/src/components/PersonCard.scss
  client/src/main.jsx
  client/src/pages/Details.jsx
  client/src/pages/Details.scss
  client/src/pages/Filter.jsx
  client/src/pages/Filter.scss
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
  client/src/pages/Search.jsx
  client/src/pages/Search.scss
  client/src/reset.css
Labels: REVIEWED

#9 S2 us5/page details
  .husky/commit-msg
  .husky/pre-commit
  client/src/App.css
  client/src/App.jsx
  client/src/components/PersonCard.jsx
  client/src/components/PersonCard.scss
  client/src/main.jsx
  client/src/pages/Details.jsx
  client/src/pages/Details.scss
  package-lock.json
  package.json
Labels: REVIEWED

#12 S3 us0/context theme
  .husky/commit-msg
  .husky/pre-commit
  client/.env.sample
  client/.gitignore
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/logo.svg
  client/src/components/PersonCard.jsx
  client/src/contexts/ThemeContext.jsx
  client/src/main.jsx
  client/src/pages/Details.jsx
  package-lock.json
Labels: REVIEWED

#11 S3 us2/homepage
  client/index.html
  client/src/App.css
  client/src/App.jsx
  client/src/assets/images/logo.jpg
  client/src/assets/images/logo.svg
  client/src/components/Card.jsx
  client/src/components/Card.scss
  client/src/components/PersonCard.jsx
  client/src/components/PersonCard.scss
  client/src/contexts/ThemeContext.jsx
  client/src/main.jsx
  client/src/pages/Details.jsx
  client/src/pages/Details.scss
  client/src/pages/Filter.jsx
  client/src/pages/Filter.scss
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
  client/src/pages/Search.jsx
  client/src/pages/Search.scss
  client/src/reset.css
  package-lock.json
Labels: REVIEWED

#15 feat: header
  client/src/App.css
  client/src/App.jsx
  client/src/App.scss
  client/src/assets/images/background.webp
  client/src/components/Card.jsx
  client/src/components/Card.scss
  client/src/components/Header.jsx
  client/src/components/Header.scss
  client/src/main.jsx
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
Labels: REVIEWED

#16 S2 us5/searchbar
  client/src/App.scss
  client/src/assets/favicon.ico
  client/src/components/SearchBar.jsx
  client/src/components/SearchBar.scss
  client/src/pages/Search.jsx
Labels: REVIEWED

#17 S3 us6/router
  client/src/App.css
  client/src/App.jsx
  client/src/components/Header.jsx
  client/src/layouts/HeaderLayout.jsx
  client/src/main.jsx
  package-lock.json
  package.json
Labels: REVIEWED

#18 feat: homepage-finish
  client/src/components/Card.jsx
  client/src/components/Card.scss
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
Labels: REVIEWED

#20 S2 us4/filter genres
  .husky/commit-msg
  .husky/pre-commit
  client/index.html
  client/src/components/FilterByGenre.jsx
  client/src/components/FilterByGenre.scss
  client/src/pages/Details.jsx
  client/src/pages/Filter.jsx
  package-lock.json
  package.json
Labels: REVIEWED

#23 feat: adding candy theme
  client/index.html
  client/src/components/Card.scss
  client/src/components/DropdownSettings.scss
  client/src/components/Header.jsx
  client/src/components/Header.scss
  client/src/pages/Details.scss
  client/src/pages/Home.jsx
  client/src/styles/candy.scss
  client/src/styles/dark.scss
  client/src/styles/light.scss
Labels: REVIEWED

#24 S3 us2/homepage finish
  client/src/components/Card.jsx
  client/src/components/Card.scss
  client/src/pages/Home.jsx
  client/src/pages/Home.scss
Labels: REVIEWED

#25 feat: fix
  client/src/components/Card.scss
Labels: REVIEWED

#27 S2 us5/searchbar
  client/src/App.scss
  client/src/components/SearchBar.jsx
  client/src/components/SearchBar.scss
Labels: REVIEWED

#29 S2 us4/filter genres
  client/package.json
  client/src/components/DropdownSettings.jsx
  client/src/components/FilterByGenre.scss
  client/src/components/PersonCard.jsx
  client/src/components/SearchBar.jsx
  client/src/contexts/ThemeContext.jsx
  client/src/main.jsx
  client/src/pages/Filter.jsx
  client/src/pages/Filter.scss
  client/src/pages/Home.jsx
Labels: CONFLICTS RESOLVED

#30 fix: add icon on the searchBar home
  client/index.html
  client/src/assets/images/camera-video.png
  client/src/assets/images/hollywood.avif
  client/src/assets/images/image.png
  client/src/components/SearchBar.jsx
  client/src/components/SearchBar.scss
Labels: CONFLICTS RESOLVED, REVIEWED

#31 fix: card of searchBar
  client/src/components/SearchBar.jsx
Labels: REVIEWED

#32 fix: mansour scss
  client/src/components/FilterByGenre.scss
  client/src/pages/Filter.scss
  client/src/styles/candy.scss
  client/src/styles/dark.scss
  client/src/styles/light.scss
Labels: REVIEWED

#33 fix: color dropdown menu
  client/src/styles/dark.scss
  client/src/styles/light.scss
Labels: REVIEWED

#35 feat: definitiv version 1.0
  client/src/assets/images/logo.svg
  client/src/components/Card.jsx
  client/src/components/PersonCard.jsx
  client/src/contexts/ThemeContext.jsx
  client/src/main.jsx
  client/src/pages/Details.jsx
  client/src/pages/Filter.jsx
  client/src/pages/Home.jsx
  client/src/pages/Search.jsx
  client/src/pages/Search.scss
  package-lock.json
Labels: REVIEWED

#40 fix: add assets in the public/dir
  client/public/_redirects
  client/public/assets/.gitkeep
  client/public/assets/images/logo.jpg
  client/src/assets/images/camera-video.png
  client/src/assets/images/hollywood.avif
  client/src/assets/images/image.png
  client/src/components/Header.jsx
Labels: REVIEW REQUESTED

#42 fix: add assets in the public/dir v2
  client/public/_redirects
Labels: REVIEWED

#44 fix: change path in index.html for adapting the new onew one of the logo
  client/index.html
Labels: REVIEWED
